"""Phase 1 seed — 개념 온톨로지.

(id, label, label_ko, domains, parent, aliases, definition)
parent 는 subclass_of 관계. '자유'처럼 하나의 이름에 여러 의미가 겹치는 개념은
반드시 하위개념으로 분리한다 — 같은 태그를 공유한다고 같은 개념이 아니다.
"""

CONCEPTS = [
    # --- metaphysics
    ("forms", "Theory of Forms", "이데아론", ["metaphysics", "epistemology"], None, ["Ideas", "이데아", "Forms"],
     "감각적 사물과 분리된, 영원불변하는 형상(이데아)이 참된 실재라는 이론"),
    ("hylomorphism", "Hylomorphism", "형상질료론", ["metaphysics"], None, ["form and matter", "형상과 질료"],
     "개별 실체는 형상과 질료의 결합이라는 이론"),
    ("substance", "Substance", "실체", ["metaphysics"], None, ["ousia"], "그 자체로 존립하는 것"),
    ("teleology", "Teleology", "목적론", ["metaphysics", "biology"], None, ["final cause", "목적인"],
     "자연물이 본성적 목적을 향한다는 설명 방식"),
    ("four-causes", "Four Causes", "4원인설", ["metaphysics", "physics"], None, [], "질료인·형상인·운동인·목적인"),
    ("mind-body-dualism", "Mind–Body Dualism", "심신이원론", ["metaphysics"], None, ["Cartesian dualism", "이원론"],
     "정신과 물체는 서로 다른 실체라는 입장"),
    ("substance-monism", "Substance Monism", "실체 일원론", ["metaphysics"], "substance", ["Deus sive Natura", "신 즉 자연"],
     "오직 하나의 실체(신 즉 자연)만 존재한다는 입장"),
    ("monad", "Monad", "모나드", ["metaphysics"], "substance", ["모나드론"], "창이 없는 단순 실체"),
    ("idealism", "Idealism", "관념론", ["metaphysics", "epistemology"], None, [], "실재가 정신적이거나 정신에 의존한다는 입장"),
    ("materialism", "Materialism", "유물론", ["metaphysics"], None, [], "물질만이 실재한다는 입장"),
    ("transcendental-idealism", "Transcendental Idealism", "초월적 관념론", ["epistemology", "metaphysics"], "idealism",
     [], "우리는 현상만 인식하며, 시공간은 감성의 형식이라는 칸트의 입장"),
    ("dialectic", "Dialectic", "변증법", ["metaphysics", "logic"], None, ["dialectics"], "모순을 통한 전개의 논리"),
    ("absolute-spirit", "Absolute Spirit", "절대정신", ["metaphysics"], "idealism", ["Geist", "정신"], "헤겔 체계의 정점"),
    ("historical-materialism", "Historical Materialism", "역사유물론", ["political-philosophy", "economics"],
     "materialism", ["materialist conception of history", "유물사관"], "물질적 생산관계가 역사를 규정한다는 이론"),
    ("will-schopenhauer", "Will as Thing-in-Itself", "물자체로서의 의지", ["metaphysics"], None, ["의지"],
     "세계의 내적 본질은 맹목적 의지라는 쇼펜하우어의 이론"),
    ("will-to-power", "Will to Power", "힘에의 의지", ["metaphysics", "ethics"], None, [], "생의 근본 충동으로서의 힘에의 의지"),
    ("eternal-recurrence", "Eternal Recurrence", "영원회귀", ["metaphysics", "ethics"], None, ["영겁회귀"], ""),
    ("nihilism", "Nihilism", "니힐리즘", ["ethics", "metaphysics"], None, ["death of God", "신의 죽음", "허무주의"],
     "최고 가치들이 스스로 가치를 잃는 사태"),
    ("being", "Being", "존재", ["metaphysics"], None, ["Sein"], "존재자를 존재자로 규정하는 것"),
    ("dasein", "Dasein", "현존재", ["metaphysics"], None, [], "자신의 존재가 문제가 되는 존재자, 인간"),
    ("determinism", "Determinism", "결정론", ["metaphysics"], None, ["necessity", "필연성"], "모든 사건은 선행 원인에 의해 결정된다"),
    ("god-existence", "Proofs of God's Existence", "신 존재 증명", ["theology", "metaphysics"], None, ["five ways", "다섯 가지 길"], ""),
    ("best-possible-world", "Best of All Possible Worlds", "최선의 세계", ["theology", "metaphysics"], None, [], ""),
    ("objective-truth", "Objective Truth", "객관적 진리", ["epistemology"], None, ["objectivity", "객관성"], ""),
    ("relativism", "Relativism", "상대주의", ["epistemology", "ethics"], None, ["perspectivism", "관점주의"], ""),
    # --- epistemology
    ("rationalism", "Rationalism", "합리론", ["epistemology"], None, ["합리주의"], "이성이 지식의 주된 원천이라는 입장"),
    ("empiricism", "Empiricism", "경험론", ["epistemology"], None, ["경험주의"], "경험이 지식의 원천이라는 입장"),
    ("innate-ideas", "Innate Ideas", "본유관념", ["epistemology"], "rationalism", ["타고난 관념"], ""),
    ("tabula-rasa", "Tabula Rasa", "백지설", ["epistemology"], "empiricism", ["white paper", "blank slate", "백지"], ""),
    ("anamnesis", "Recollection (Anamnesis)", "상기설", ["epistemology"], None, ["recollection", "상기"],
     "배움은 영혼이 이미 알던 것을 떠올리는 것이라는 플라톤의 이론"),
    ("cogito", "Cogito", "코기토", ["epistemology", "metaphysics"], None, ["cogito ergo sum", "나는 생각한다 그러므로 존재한다"], ""),
    ("skepticism", "Skepticism", "회의주의", ["epistemology"], None, ["methodic doubt", "방법적 회의"], ""),
    ("problem-of-induction", "Problem of Induction", "귀납의 문제", ["epistemology", "philosophy-of-science"], "skepticism",
     ["induction", "귀납"], "관찰된 사례에서 관찰되지 않은 사례로의 추론은 이성적으로 정당화되지 않는다는 문제"),
    ("synthetic-a-priori", "Synthetic A Priori", "선험적 종합판단", ["epistemology"], None, ["종합적 선천판단"], ""),
    ("phenomenology-concept", "Phenomenological Method", "현상학적 방법", ["epistemology"], None,
     ["phenomenology", "현상학", "사태 자체로"], "의식에 주어지는 그대로를 기술하는 방법"),
    ("epoche", "Epoché", "판단중지", ["epistemology"], "phenomenology-concept", ["bracketing", "에포케", "현상학적 환원"], ""),
    ("intentionality", "Intentionality", "지향성", ["epistemology"], None, [], "의식은 언제나 무엇에 대한 의식이다"),
    ("falsifiability", "Falsifiability", "반증가능성", ["philosophy-of-science"], None, ["falsification", "반증주의"], ""),
    ("paradigm", "Paradigm", "패러다임", ["philosophy-of-science"], None, ["normal science", "정상과학", "과학혁명"], ""),
    ("picture-theory", "Picture Theory of Meaning", "그림이론", ["philosophy-of-language"], None, [], ""),
    ("language-game", "Language-Game", "언어게임", ["philosophy-of-language"], None, ["meaning as use", "family resemblance", "가족유사성"], ""),
    ("logical-analysis", "Logical Analysis", "논리적 분석", ["philosophy-of-language", "logic"], None,
     ["theory of descriptions", "기술 이론"], ""),
    ("logicism", "Logicism", "논리주의", ["mathematical-logic"], None, [], "수학은 논리로 환원된다"),
    ("socratic-method", "Socratic Method", "소크라테스적 문답법", ["epistemology", "ethics"], None,
     ["elenchus", "Socratic ignorance", "무지의 지", "산파술"], ""),
    ("experimental-method", "Experimental Method", "실험적 방법", ["philosophy-of-science", "physics"], None, [], ""),
    ("truth-as-subjectivity", "Truth as Subjectivity", "주체성으로서의 진리", ["epistemology", "theology"], None, [], ""),
    ("mathematization-of-nature", "Mathematization of Nature", "자연의 수학화", ["physics", "mathematics"], None,
     ["mathematical physics"], "자연을 수학적 법칙으로 기술하려는 기획"),
    # --- ethics
    ("virtue", "Virtue", "덕", ["ethics"], None, ["arete", "아레테"], ""),
    ("eudaimonia", "Eudaimonia", "에우다이모니아", ["ethics"], None, ["happiness", "행복", "flourishing"], ""),
    ("ataraxia", "Ataraxia", "평정", ["ethics"], None, ["tranquility", "마음의 평정"], ""),
    ("categorical-imperative", "Categorical Imperative", "정언명령", ["ethics"], None, [], ""),
    ("utilitarianism", "Utilitarianism", "공리주의", ["ethics"], None, ["greatest happiness", "최대 행복"], ""),
    ("harm-principle", "Harm Principle", "해악의 원리", ["political-philosophy", "ethics"], None, [], ""),
    ("master-slave-morality", "Master and Slave Morality", "주인도덕과 노예도덕", ["ethics"], None, ["노예도덕"], ""),
    ("existentialism-concept", "Existence Precedes Essence", "실존은 본질에 앞선다", ["ethics", "metaphysics"], None,
     ["existentialism", "실존주의", "실존"], ""),
    ("absurd", "The Absurd", "부조리", ["ethics"], None, [], "의미를 구하는 인간과 침묵하는 세계의 대면"),
    ("bad-faith", "Bad Faith", "자기기만", ["ethics"], None, ["mauvaise foi"], ""),
    ("authenticity", "Authenticity", "본래성", ["ethics", "metaphysics"], None, ["Eigentlichkeit", "진정성"], ""),
    ("is-ought", "Is–Ought Problem", "존재-당위 문제", ["ethics"], None, ["Hume's guillotine"], ""),
    ("faith-and-reason", "Faith and Reason", "신앙과 이성", ["theology"], None, [], ""),
    ("leap-of-faith", "Leap of Faith", "신앙의 도약", ["theology", "ethics"], None, [], ""),
    # --- political
    ("justice", "Justice", "정의", ["political-philosophy", "ethics"], None, ["dikaiosyne"], ""),
    ("justice-as-fairness", "Justice as Fairness", "공정으로서의 정의", ["political-philosophy"], "justice", [], ""),
    ("veil-of-ignorance", "Veil of Ignorance", "무지의 베일", ["political-philosophy"], None, ["original position", "원초적 입장"], ""),
    ("ideal-state", "Ideal State", "이상국가", ["political-philosophy"], None, ["kallipolis"], ""),
    ("philosopher-king", "Philosopher-King", "철인정치", ["political-philosophy"], "ideal-state", ["철인왕"], ""),
    ("social-contract-concept", "Social Contract", "사회계약", ["political-philosophy"], None, ["social contract", "사회계약론"], ""),
    ("state-of-nature", "State of Nature", "자연상태", ["political-philosophy"], None, [], ""),
    ("sovereignty", "Sovereignty", "주권", ["political-philosophy", "law"], None, [], ""),
    ("natural-law", "Natural Law", "자연법", ["law", "ethics", "political-philosophy"], None, ["lex naturalis"], ""),
    ("natural-rights", "Natural Rights", "자연권", ["political-philosophy", "law"], None, ["life, liberty, property", "천부인권"], ""),
    ("general-will", "General Will", "일반의지", ["political-philosophy"], None, ["volonté générale"], ""),
    ("political-realism", "Political Realism", "정치적 현실주의", ["political-philosophy"], None, ["virtù", "realpolitik"], ""),
    ("alienation", "Alienation", "소외", ["political-philosophy", "economics"], None, ["estranged labour", "소외된 노동"], ""),
    ("class-struggle", "Class Struggle", "계급투쟁", ["political-philosophy", "economics"], None, [], ""),
    ("open-society", "Open Society", "열린사회", ["political-philosophy"], None, [], ""),
    ("two-cities", "Two Cities", "두 도성", ["theology", "political-philosophy"], None, ["신국"], ""),
    ("enlightenment-concept", "Enlightenment as Autonomy of Reason", "계몽(이성의 자율)", ["political-philosophy", "ethics"],
     None, ["sapere aude", "계몽"], ""),
    ("modernity", "Modernity", "근대성", ["political-philosophy", "sociology"], None, ["modern society"],
     "전통적 질서의 해체와 합리화·자본주의·세속화로 특징지어지는 근대의 조건"),
    ("critique-of-religion", "Critique of Religion", "종교 비판", ["theology", "political-philosophy"], None, [], ""),
    ("ideology-critique", "Ideology Critique / Genealogy of Values", "이데올로기 비판·가치의 계보", ["political-philosophy", "ethics"],
     None, ["ideology", "genealogy", "이데올로기", "계보학"], "지배적 관념·가치가 권력관계에서 기원했음을 폭로하는 비판"),
    ("individualism", "Individualism", "개인주의", ["political-philosophy"], None, [], ""),
    ("collectivism", "Collectivism", "집단주의", ["political-philosophy"], None, ["socialism", "사회주의"], ""),
    ("private-property", "Private Property", "사유재산", ["economics", "political-philosophy"], None, ["property", "재산"], ""),
    ("labor-theory-of-property", "Labor Theory of Property", "노동 소유론", ["political-philosophy", "economics"],
     "private-property", [], "노동을 섞은 것이 소유가 된다는 로크의 이론"),
    ("central-planning", "Central Planning", "중앙계획", ["economics"], "collectivism", ["planned economy", "계획경제"], ""),
    # --- freedom family
    ("freedom", "Freedom", "자유", ["political-philosophy", "ethics", "metaphysics"], None, ["liberty"], ""),
    ("negative-freedom", "Negative Freedom", "소극적 자유", ["political-philosophy"], "freedom", ["freedom from"],
     "외부의 간섭·강제가 없는 상태"),
    ("positive-freedom", "Positive Freedom", "적극적 자유", ["political-philosophy"], "freedom", ["freedom to", "self-mastery"],
     "자기 자신의 주인이 되는 것, 자기실현"),
    ("political-freedom", "Political Freedom", "정치적 자유", ["political-philosophy"], "freedom", [], ""),
    ("economic-freedom", "Economic Freedom", "경제적 자유", ["economics"], "freedom", ["free market"], ""),
    ("moral-freedom", "Moral Freedom (Autonomy)", "도덕적 자유(자율)", ["ethics"], "positive-freedom", ["autonomy", "자율"],
     "스스로 부과한 법칙에 따르는 것"),
    ("free-will", "Free Will (Metaphysical Freedom)", "자유의지", ["metaphysics"], "freedom", ["liberum arbitrium", "형이상학적 자유"], ""),
    ("existential-freedom", "Existential Freedom", "실존적 자유", ["ethics"], "freedom", ["condemned to be free"], ""),
    ("epistemic-freedom", "Freedom of Thought", "사상의 자유", ["political-philosophy"], "freedom",
     ["freedom of expression", "freedom to philosophize", "표현의 자유"], ""),
    ("inner-freedom", "Inner Freedom", "내면의 자유", ["ethics"], "positive-freedom", ["dichotomy of control", "통제의 이분법"],
     "통제할 수 있는 것과 없는 것의 구분에 기초한 스토아적 자유"),
    ("freedom-as-necessity", "Freedom as Understanding Necessity", "필연성의 인식으로서의 자유", ["metaphysics", "ethics"],
     "positive-freedom", [], ""),
    # --- economics
    ("division-of-labor", "Division of Labor", "분업", ["economics", "political-philosophy"], None, ["specialization", "전문화"], ""),
    ("self-interest", "Self-Interest", "자기이익", ["economics", "ethics"], None, [], ""),
    ("invisible-hand", "Invisible Hand", "보이지 않는 손", ["economics"], None, ["market order", "시장"], ""),
    ("spontaneous-order", "Spontaneous Order", "자생적 질서", ["economics", "political-philosophy"], None, ["catallaxy"], ""),
    ("dispersed-knowledge", "Dispersed Knowledge", "분산된 지식", ["economics", "epistemology"], None,
     ["knowledge problem", "price signals", "가격 신호"], ""),
    ("labor-theory-of-value", "Labor Theory of Value", "노동가치론", ["economics"], None, [], ""),
    ("surplus-value", "Surplus Value", "잉여가치", ["economics"], None, ["exploitation", "착취"], ""),
    ("comparative-advantage", "Comparative Advantage", "비교우위", ["economics"], None, [], ""),
    ("effective-demand", "Effective Demand", "유효수요", ["economics"], None, ["aggregate demand", "총수요"], ""),
    ("just-exchange", "Just Exchange", "정의로운 교환", ["economics", "ethics"], "justice",
     ["commutative justice", "money as measure", "교환 정의", "화폐"], ""),
    ("just-price", "Just Price", "공정가격", ["economics", "theology"], None, ["iustum pretium"], ""),
    # --- science & mathematics
    ("universal-gravitation", "Universal Gravitation", "만유인력", ["physics"], None, ["gravity", "중력"], ""),
    ("absolute-space", "Absolute Space", "절대공간", ["physics", "metaphysics"], None, [], ""),
    ("relational-space", "Relational Space", "관계적 공간", ["physics", "metaphysics"], None, [], ""),
    ("relativity", "Theory of Relativity", "상대성이론", ["physics"], None, ["special relativity", "특수상대성"], ""),
    ("analytic-geometry", "Analytic Geometry", "해석기하학", ["geometry", "algebra"], None, ["coordinate geometry", "좌표"], ""),
    ("calculus", "Calculus", "미적분", ["analysis"], None, ["infinitesimal calculus", "fluxions", "미분"], ""),
    ("mechanism", "Mechanical Philosophy", "기계론적 자연관", ["physics", "metaphysics"], None, ["mechanism", "기계론"], ""),
]

# 개념 간 관계 (source, predicate, target, evidence?) — 증거가 필요한 관계는 relations.py 에 있다.
CONCEPT_RELATIONS = [
    ("rationalism", "opposed_to", "empiricism"),
    ("idealism", "opposed_to", "materialism"),
    ("free-will", "opposed_to", "determinism"),
    ("innate-ideas", "opposed_to", "tabula-rasa"),
    ("individualism", "opposed_to", "collectivism"),
    ("objective-truth", "opposed_to", "relativism"),
    ("absolute-space", "opposed_to", "relational-space"),
    ("negative-freedom", "contrasts_with", "positive-freedom"),
    ("spontaneous-order", "opposed_to", "central-planning"),
    ("eudaimonia", "contrasts_with", "ataraxia"),
    ("categorical-imperative", "contrasts_with", "utilitarianism"),
    ("master-slave-morality", "contrasts_with", "categorical-imperative"),
    ("mind-body-dualism", "contrasts_with", "substance-monism"),
    ("faith-and-reason", "contrasts_with", "leap-of-faith"),
    ("falsifiability", "contrasts_with", "paradigm"),
    ("hylomorphism", "contrasts_with", "forms"),
    ("social-contract-concept", "presupposes", "state-of-nature"),
    ("veil-of-ignorance", "depends_on", "social-contract-concept"),
    ("justice-as-fairness", "depends_on", "veil-of-ignorance"),
    ("natural-law", "presupposes", "teleology"),
    ("natural-rights", "depends_on", "natural-law"),
    ("four-causes", "depends_on", "teleology"),
    ("cogito", "depends_on", "skepticism"),
    ("falsifiability", "depends_on", "problem-of-induction"),
    ("dasein", "depends_on", "being"),
    ("class-struggle", "depends_on", "historical-materialism"),
    ("surplus-value", "depends_on", "labor-theory-of-value"),
    ("philosopher-king", "depends_on", "forms"),
    ("general-will", "depends_on", "social-contract-concept"),
    ("sovereignty", "depends_on", "social-contract-concept"),
    ("categorical-imperative", "depends_on", "moral-freedom"),
    ("invisible-hand", "depends_on", "self-interest"),
    ("invisible-hand", "depends_on", "division-of-labor"),
    ("spontaneous-order", "depends_on", "dispersed-knowledge"),
    ("universal-gravitation", "depends_on", "calculus"),
    ("universal-gravitation", "depends_on", "mathematization-of-nature"),
    ("analytic-geometry", "depends_on", "mathematization-of-nature"),
    ("bad-faith", "depends_on", "existential-freedom"),
    ("existential-freedom", "depends_on", "existentialism-concept"),
    ("nihilism", "contrasts_with", "will-to-power"),
    ("mechanism", "contrasts_with", "teleology"),
    ("ideology-critique", "depends_on", "modernity"),
    ("critique-of-religion", "contrasts_with", "faith-and-reason"),
]
