"""Phase 1 seed — 인물과 저작.

연도는 근사치다. 고대 저작의 연대는 학계 추정치(c.)를 사용했다.
"""

# (id, label, label_ko, born, died, domains, schools, institutions, description)
PERSONS = [
    ("person:socrates", "Socrates", "소크라테스", -470, -399, ["ethics", "epistemology"], [], [],
     "저술을 남기지 않았고 플라톤·크세노폰의 기록으로 전해지는 아테네의 철학자"),
    ("person:plato", "Plato", "플라톤", -428, -348, ["metaphysics", "political-philosophy", "epistemology"],
     ["platonism"], ["academy"], "이데아론과 이상국가론을 제시한 아테네의 철학자"),
    ("person:aristotle", "Aristotle", "아리스토텔레스", -384, -322,
     ["metaphysics", "ethics", "logic", "political-philosophy", "biology"], ["aristotelianism"], ["lyceum"],
     "형상질료론·목적론·덕 윤리·논리학의 체계를 세운 철학자"),
    ("person:epicurus", "Epicurus", "에피쿠로스", -341, -270, ["ethics"], ["epicureanism"], [],
     "원자론과 평정의 윤리를 설파한 헬레니즘 철학자"),
    ("person:epictetus", "Epictetus", "에픽테토스", 50, 135, ["ethics"], ["stoicism"], [],
     "노예 출신의 스토아 철학자 — 대표적 스토아 철학자로 선정"),
    ("person:augustine", "Augustine of Hippo", "아우구스티누스", 354, 430, ["theology", "metaphysics"],
     [], [], "플라톤주의와 기독교 신학을 종합한 교부"),
    ("person:aquinas", "Thomas Aquinas", "토마스 아퀴나스", 1225, 1274,
     ["theology", "metaphysics", "ethics", "political-philosophy"], ["scholasticism", "natural-law-tradition"],
     ["university-of-paris"], "아리스토텔레스 철학과 기독교 신학을 종합한 스콜라 철학자"),
    ("person:machiavelli", "Niccolò Machiavelli", "마키아벨리", 1469, 1527, ["political-philosophy", "politics"],
     [], [], "정치를 도덕에서 분리해 '실제로 일어나는 일'로 분석한 피렌체의 사상가"),
    ("person:hooker", "Richard Hooker", "리처드 후커", 1554, 1600, ["theology", "political-philosophy"],
     ["natural-law-tradition"], ["oxford"], "토마스주의 자연법을 영국 국교회 신학에 도입한 신학자"),
    ("person:hobbes", "Thomas Hobbes", "홉스", 1588, 1679, ["political-philosophy", "metaphysics"],
     ["social-contract"], ["oxford"], "자연상태와 사회계약으로 주권을 정당화한 철학자"),
    ("person:descartes", "René Descartes", "데카르트", 1596, 1650,
     ["metaphysics", "epistemology", "mathematics"], ["continental-rationalism"], [],
     "방법적 회의와 코기토, 해석기하학의 창시자"),
    ("person:spinoza", "Baruch Spinoza", "스피노자", 1632, 1677,
     ["metaphysics", "ethics", "political-philosophy"], ["continental-rationalism"], [],
     "신 즉 자연의 실체 일원론을 전개한 철학자"),
    ("person:locke", "John Locke", "로크", 1632, 1704, ["epistemology", "political-philosophy"],
     ["british-empiricism", "social-contract", "liberalism"], ["oxford"], "경험론과 자연권 자유주의의 철학자"),
    ("person:newton", "Isaac Newton", "뉴턴", 1643, 1727, ["physics", "mathematics"], [], ["cambridge"],
     "만유인력과 운동법칙, 미적분을 정립한 자연철학자"),
    ("person:leibniz", "Gottfried Wilhelm Leibniz", "라이프니츠", 1646, 1716,
     ["metaphysics", "mathematics", "logic"], ["continental-rationalism"], [],
     "모나드론과 미적분(독립 발견)의 철학자·수학자"),
    ("person:hume", "David Hume", "흄", 1711, 1776, ["epistemology", "ethics"], ["british-empiricism"], [],
     "인과·귀납에 대한 회의를 제기한 스코틀랜드 계몽주의 철학자"),
    ("person:rousseau", "Jean-Jacques Rousseau", "루소", 1712, 1778, ["political-philosophy", "ethics"],
     ["social-contract", "enlightenment"], [], "일반의지와 사회계약론의 사상가"),
    ("person:smith", "Adam Smith", "애덤 스미스", 1723, 1790, ["economics", "ethics"],
     ["classical-economics", "enlightenment"], [], "분업과 시장 질서를 분석한 정치경제학의 창시자"),
    ("person:kant", "Immanuel Kant", "칸트", 1724, 1804, ["epistemology", "ethics", "metaphysics"],
     ["german-idealism", "enlightenment"], ["konigsberg"], "비판철학으로 합리론과 경험론을 종합한 철학자"),
    ("person:jefferson", "Thomas Jefferson", "제퍼슨", 1743, 1826, ["politics"], ["liberalism"], [],
     "미국 독립선언서의 기초자"),
    ("person:hegel", "G. W. F. Hegel", "헤겔", 1770, 1831, ["metaphysics", "political-philosophy"],
     ["german-idealism"], ["berlin"], "변증법과 절대정신의 체계 철학자"),
    ("person:ricardo", "David Ricardo", "리카도", 1772, 1823, ["economics"], ["classical-economics"], [],
     "비교우위와 노동가치론을 정식화한 경제학자"),
    ("person:schopenhauer", "Arthur Schopenhauer", "쇼펜하우어", 1788, 1860, ["metaphysics", "ethics"],
     [], ["berlin"], "의지를 물자체로 본 비관주의 철학자"),
    ("person:mill", "John Stuart Mill", "존 스튜어트 밀", 1806, 1873, ["ethics", "political-philosophy", "economics"],
     ["utilitarianism", "liberalism"], [], "해악의 원리와 공리주의의 철학자"),
    ("person:kierkegaard", "Søren Kierkegaard", "키르케고르", 1813, 1855, ["theology", "ethics"],
     ["existentialism"], [], "주체성과 신앙의 도약을 강조한 실존주의의 선구자"),
    ("person:marx", "Karl Marx", "마르크스", 1818, 1883, ["economics", "political-philosophy"], ["marxism"],
     ["berlin"], "역사유물론과 자본주의 비판의 사상가"),
    ("person:engels", "Friedrich Engels", "엥겔스", 1820, 1895, ["economics", "political-philosophy"],
     ["marxism"], [], "마르크스의 공저자"),
    ("person:nietzsche", "Friedrich Nietzsche", "니체", 1844, 1900, ["ethics", "metaphysics"], [], [],
     "가치의 전도와 힘에의 의지를 말한 철학자"),
    ("person:husserl", "Edmund Husserl", "후설", 1859, 1938, ["epistemology"], ["phenomenology"], ["freiburg"],
     "현상학의 창시자"),
    ("person:russell", "Bertrand Russell", "러셀", 1872, 1970, ["logic", "mathematical-logic", "philosophy-of-language"],
     ["analytic-philosophy"], ["cambridge"], "논리주의와 기술 이론의 분석철학자"),
    ("person:einstein", "Albert Einstein", "아인슈타인", 1879, 1955, ["physics"], [], [], "상대성이론의 물리학자"),
    ("person:keynes", "John Maynard Keynes", "케인스", 1883, 1946, ["economics"], ["keynesianism"], ["cambridge"],
     "유효수요 이론의 경제학자"),
    ("person:heidegger", "Martin Heidegger", "하이데거", 1889, 1976, ["metaphysics"], ["phenomenology", "existentialism"],
     ["freiburg"], "존재 물음과 현존재 분석의 철학자"),
    ("person:wittgenstein", "Ludwig Wittgenstein", "비트겐슈타인", 1889, 1951,
     ["philosophy-of-language", "logic"], ["analytic-philosophy"], ["cambridge"], "그림이론과 언어게임의 철학자"),
    ("person:hayek", "Friedrich Hayek", "하이에크", 1899, 1992, ["economics", "political-philosophy"],
     ["austrian-school", "liberalism"], ["lse"], "분산된 지식과 자생적 질서의 경제학자"),
    ("person:popper", "Karl Popper", "포퍼", 1902, 1994, ["philosophy-of-science", "political-philosophy"],
     ["critical-rationalism"], ["lse"], "반증주의와 열린사회의 철학자"),
    ("person:sartre", "Jean-Paul Sartre", "사르트르", 1905, 1980, ["metaphysics", "ethics"], ["existentialism"], [],
     "실존은 본질에 앞선다고 말한 실존주의자"),
    ("person:berlin", "Isaiah Berlin", "이사야 벌린", 1909, 1997, ["political-philosophy"], ["liberalism"], ["oxford"],
     "소극적·적극적 자유를 구분한 정치철학자"),
    ("person:camus", "Albert Camus", "카뮈", 1913, 1960, ["ethics", "literature"], [], [], "부조리와 반항의 작가·철학자"),
    ("person:rawls", "John Rawls", "롤스", 1921, 2002, ["political-philosophy", "ethics"], ["social-contract", "liberalism"],
     ["harvard"], "공정으로서의 정의의 정치철학자"),
    ("person:kuhn", "Thomas Kuhn", "쿤", 1922, 1996, ["philosophy-of-science"], [], ["harvard"],
     "패러다임과 과학혁명의 구조를 제시한 과학철학자"),
]

# (id, label, label_ko, author(s), year, domains, description)
WORKS = [
    ("work:apology", "Apology", "소크라테스의 변론", ["plato"], -399, ["ethics"], "소크라테스 재판의 변론 (c. 399 BC 이후)"),
    ("work:meno", "Meno", "메논", ["plato"], -385, ["epistemology"], "덕의 교육 가능성과 상기설 (c.)"),
    ("work:republic", "Republic", "국가", ["plato"], -375, ["political-philosophy", "metaphysics"],
     "정의·이상국가·철인정치·이데아 (c.)"),
    ("work:symposium", "Symposium", "향연", ["plato"], -385, ["ethics"], "에로스와 아름다움의 이데아 (c.)"),
    ("work:timaeus", "Timaeus", "티마이오스", ["plato"], -360, ["metaphysics"], "우주론 (c.)"),
    ("work:metaphysics", "Metaphysics", "형이상학", ["aristotle"], -340, ["metaphysics"], "실체론·이데아론 비판 (c.)"),
    ("work:physics", "Physics", "자연학", ["aristotle"], -350, ["metaphysics", "physics"], "4원인설과 운동론 (c.)"),
    ("work:nicomachean-ethics", "Nicomachean Ethics", "니코마코스 윤리학", ["aristotle"], -340, ["ethics", "economics"],
     "행복·덕·정의로운 교환 (c.)"),
    ("work:politics", "Politics", "정치학", ["aristotle"], -340, ["political-philosophy", "economics"],
     "폴리스·사유재산·플라톤 비판 (c.)"),
    ("work:letter-to-menoeceus", "Letter to Menoeceus", "메노이케우스에게 보내는 편지", ["epicurus"], -300, ["ethics"], "(c.)"),
    ("work:enchiridion", "Enchiridion", "엥케이리디온", ["epictetus"], 125, ["ethics"], "아리아노스가 편찬한 에픽테토스의 가르침 (c.)"),
    ("work:de-libero-arbitrio", "On Free Choice of the Will", "자유의지론", ["augustine"], 395, ["theology", "metaphysics"], "(388–395)"),
    ("work:confessions", "Confessions", "고백록", ["augustine"], 400, ["theology"], "(397–400)"),
    ("work:city-of-god", "City of God", "신국론", ["augustine"], 426, ["theology", "political-philosophy"], "(413–426)"),
    ("work:summa-theologiae", "Summa Theologiae", "신학대전", ["aquinas"], 1270, ["theology", "ethics", "metaphysics"], "(1265–1274)"),
    ("work:the-prince", "The Prince", "군주론", ["machiavelli"], 1513, ["political-philosophy"], "1513년 집필, 1532년 출간"),
    ("work:laws-ecclesiastical-polity", "Of the Laws of Ecclesiastical Polity", "교회 정체의 법", ["hooker"], 1594,
     ["theology", "political-philosophy"], ""),
    ("work:discourse-on-method", "Discourse on the Method", "방법서설", ["descartes"], 1637, ["epistemology"], ""),
    ("work:la-geometrie", "La Géométrie", "기하학", ["descartes"], 1637, ["geometry"], "『방법서설』의 부록"),
    ("work:meditations", "Meditations on First Philosophy", "성찰", ["descartes"], 1641, ["metaphysics", "epistemology"],
     "반론과 답변(Objections and Replies) 포함"),
    ("work:leviathan", "Leviathan", "리바이어던", ["hobbes"], 1651, ["political-philosophy"], ""),
    ("work:principles-cartesian", "Principles of Cartesian Philosophy", "데카르트 철학의 원리", ["spinoza"], 1663,
     ["metaphysics"], ""),
    ("work:ttp", "Theological-Political Treatise", "신학정치론", ["spinoza"], 1670, ["political-philosophy", "theology"], ""),
    ("work:ethics-spinoza", "Ethics", "에티카", ["spinoza"], 1677, ["metaphysics", "ethics"], ""),
    ("work:discourse-on-metaphysics", "Discourse on Metaphysics", "형이상학 논고", ["leibniz"], 1686, ["metaphysics"], ""),
    ("work:principia", "Philosophiæ Naturalis Principia Mathematica", "프린키피아", ["newton"], 1687,
     ["physics", "mathematics"], "1713년 제2판에 일반 주해 추가"),
    ("work:essay-human-understanding", "An Essay Concerning Human Understanding", "인간지성론", ["locke"], 1689,
     ["epistemology"], ""),
    ("work:two-treatises", "Two Treatises of Government", "통치론", ["locke"], 1689, ["political-philosophy"], ""),
    ("work:new-essays", "New Essays on Human Understanding", "신인간지성론", ["leibniz"], 1704, ["epistemology"],
     "1704년 완성, 1765년 출간"),
    ("work:monadology", "Monadology", "모나드론", ["leibniz"], 1714, ["metaphysics"], ""),
    ("work:leibniz-clarke", "Leibniz–Clarke Correspondence", "라이프니츠–클라크 서한", ["leibniz"], 1716,
     ["metaphysics", "physics"], "뉴턴 측 클라크와의 공간·시간 논쟁"),
    ("work:treatise-human-nature", "A Treatise of Human Nature", "인간 본성론", ["hume"], 1739,
     ["epistemology", "ethics"], "부제: 도덕적 주제에 실험적 추론 방법을 도입하려는 시도"),
    ("work:enquiry-human-understanding", "An Enquiry Concerning Human Understanding", "인간지성에 관한 탐구", ["hume"],
     1748, ["epistemology"], ""),
    ("work:discourse-inequality", "Discourse on Inequality", "인간 불평등 기원론", ["rousseau"], 1755,
     ["political-philosophy"], ""),
    ("work:universal-natural-history", "Universal Natural History and Theory of the Heavens",
     "일반 자연사와 천체 이론", ["kant"], 1755, ["astronomy", "physics"], ""),
    ("work:theory-moral-sentiments", "The Theory of Moral Sentiments", "도덕감정론", ["smith"], 1759, ["ethics"], ""),
    ("work:social-contract", "The Social Contract", "사회계약론", ["rousseau"], 1762, ["political-philosophy"], ""),
    ("work:kant-remarks", "Remarks in the Observations on the Feeling of the Beautiful and Sublime",
     "『미와 숭고의 감정에 관한 고찰』 메모", ["kant"], 1765, ["ethics"], "1764–65년 자필 메모"),
    ("work:wealth-of-nations", "The Wealth of Nations", "국부론", ["smith"], 1776, ["economics"], ""),
    ("work:declaration-of-independence", "Declaration of Independence", "독립선언서", ["jefferson"], 1776, ["politics"], ""),
    ("work:letter-to-henry-lee", "Letter to Henry Lee (8 May 1825)", "헨리 리에게 보낸 편지", ["jefferson"], 1825,
     ["politics"], "독립선언서의 사상적 원천을 회고한 편지"),
    ("work:critique-of-pure-reason", "Critique of Pure Reason", "순수이성비판", ["kant"], 1781,
     ["epistemology", "metaphysics"], "1787년 제2판(B)"),
    ("work:prolegomena", "Prolegomena to Any Future Metaphysics", "형이상학 서설", ["kant"], 1783, ["metaphysics"], ""),
    ("work:what-is-enlightenment", "An Answer to the Question: What is Enlightenment?", "계몽이란 무엇인가", ["kant"],
     1784, ["political-philosophy"], ""),
    ("work:groundwork", "Groundwork of the Metaphysics of Morals", "도덕형이상학 정초", ["kant"], 1785, ["ethics"], ""),
    ("work:faith-and-knowledge", "Faith and Knowledge", "믿음과 지식", ["hegel"], 1802, ["metaphysics"], ""),
    ("work:phenomenology-of-spirit", "Phenomenology of Spirit", "정신현상학", ["hegel"], 1807, ["metaphysics"], ""),
    ("work:principles-political-economy", "On the Principles of Political Economy and Taxation", "정치경제학과 과세의 원리",
     ["ricardo"], 1817, ["economics"], ""),
    ("work:world-as-will", "The World as Will and Representation", "의지와 표상으로서의 세계", ["schopenhauer"], 1818,
     ["metaphysics"], "1844년 제2판"),
    ("work:philosophy-of-right", "Elements of the Philosophy of Right", "법철학", ["hegel"], 1820,
     ["political-philosophy"], ""),
    ("work:lectures-philosophy-of-history", "Lectures on the Philosophy of History", "역사철학 강의", ["hegel"], 1837,
     ["political-philosophy"], "사후 출간"),
    ("work:marx-dissertation", "The Difference Between the Democritean and Epicurean Philosophy of Nature",
     "데모크리토스와 에피쿠로스 자연철학의 차이", ["marx"], 1841, ["metaphysics"], "박사학위 논문"),
    ("work:either-or", "Either/Or", "이것이냐 저것이냐", ["kierkegaard"], 1843, ["ethics"], ""),
    ("work:fear-and-trembling", "Fear and Trembling", "두려움과 떨림", ["kierkegaard"], 1843, ["theology", "ethics"], ""),
    ("work:manuscripts-1844", "Economic and Philosophic Manuscripts of 1844", "1844년 경제학·철학 수고", ["marx"], 1844,
     ["economics"], "1932년 출간"),
    ("work:critique-hegel-right-intro", "A Contribution to the Critique of Hegel's Philosophy of Right: Introduction",
     "헤겔 법철학 비판 서설", ["marx"], 1844, ["political-philosophy", "theology"], "Deutsch-Französische Jahrbücher, 1844"),
    ("work:german-ideology", "The German Ideology", "독일 이데올로기", ["marx", "engels"], 1846,
     ["political-philosophy"], "1846년 집필, 1932년 출간"),
    ("work:theses-on-feuerbach", "Theses on Feuerbach", "포이어바흐에 관한 테제", ["marx"], 1845, ["metaphysics"], ""),
    ("work:concluding-postscript", "Concluding Unscientific Postscript", "철학적 단편에 대한 비학문적 후서",
     ["kierkegaard"], 1846, ["theology", "epistemology"], ""),
    ("work:communist-manifesto", "The Communist Manifesto", "공산당 선언", ["marx", "engels"], 1848,
     ["political-philosophy", "economics"], ""),
    ("work:on-liberty", "On Liberty", "자유론", ["mill"], 1859, ["political-philosophy"], ""),
    ("work:utilitarianism", "Utilitarianism", "공리주의", ["mill"], 1863, ["ethics"], ""),
    ("work:capital", "Capital, Vol. I", "자본 1권", ["marx"], 1867, ["economics"], "제2판(1873) 후기 포함"),
    ("work:untimely-schopenhauer", "Schopenhauer as Educator", "교육자로서의 쇼펜하우어", ["nietzsche"], 1874, ["ethics"],
     "『반시대적 고찰』 제3편"),
    ("work:gay-science", "The Gay Science", "즐거운 학문", ["nietzsche"], 1882, ["ethics"], ""),
    ("work:zarathustra", "Thus Spoke Zarathustra", "차라투스트라는 이렇게 말했다", ["nietzsche"], 1883,
     ["ethics", "literature"], ""),
    ("work:beyond-good-and-evil", "Beyond Good and Evil", "선악의 저편", ["nietzsche"], 1886, ["ethics", "metaphysics"], ""),
    ("work:genealogy-of-morals", "On the Genealogy of Morals", "도덕의 계보", ["nietzsche"], 1887, ["ethics"], ""),
    ("work:twilight-of-idols", "Twilight of the Idols", "우상의 황혼", ["nietzsche"], 1889, ["metaphysics"], ""),
    ("work:logical-investigations", "Logical Investigations", "논리연구", ["husserl"], 1900, ["epistemology", "logic"], ""),
    ("work:on-denoting", "On Denoting", "지시에 관하여", ["russell"], 1905, ["philosophy-of-language"], ""),
    ("work:special-relativity", "On the Electrodynamics of Moving Bodies", "움직이는 물체의 전기역학에 관하여",
     ["einstein"], 1905, ["physics"], "특수상대성이론 논문"),
    ("work:principia-mathematica", "Principia Mathematica", "수학 원리", ["russell"], 1910, ["mathematical-logic"],
     "화이트헤드와 공저 (1910–1913)"),
    ("work:ideas-i", "Ideas I", "이념들 I", ["husserl"], 1913, ["epistemology"], ""),
    ("work:tractatus", "Tractatus Logico-Philosophicus", "논리철학논고", ["wittgenstein"], 1921,
     ["philosophy-of-language", "logic"], ""),
    ("work:being-and-time", "Being and Time", "존재와 시간", ["heidegger"], 1927, ["metaphysics"], ""),
    ("work:hayek-review-keynes", "Reflections on the Pure Theory of Money of Mr. J. M. Keynes",
     "케인스의 화폐 순수이론에 대한 성찰", ["hayek"], 1931, ["economics"], "Economica, 1931"),
    ("work:logic-scientific-discovery", "The Logic of Scientific Discovery", "과학적 발견의 논리", ["popper"], 1934,
     ["philosophy-of-science"], "독일어판 1934, 영어판 1959"),
    ("work:general-theory", "The General Theory of Employment, Interest and Money", "고용·이자 및 화폐의 일반이론",
     ["keynes"], 1936, ["economics"], ""),
    ("work:myth-of-sisyphus", "The Myth of Sisyphus", "시지프 신화", ["camus"], 1942, ["ethics"], ""),
    ("work:being-and-nothingness", "Being and Nothingness", "존재와 무", ["sartre"], 1943, ["metaphysics"],
     "부제: 현상학적 존재론 시론"),
    ("work:road-to-serfdom", "The Road to Serfdom", "노예의 길", ["hayek"], 1944, ["political-philosophy", "economics"], ""),
    ("work:open-society", "The Open Society and Its Enemies", "열린사회와 그 적들", ["popper"], 1945,
     ["political-philosophy"], ""),
    ("work:use-of-knowledge", "The Use of Knowledge in Society", "사회에서 지식의 활용", ["hayek"], 1945, ["economics"],
     "American Economic Review, 1945"),
    ("work:existentialism-humanism", "Existentialism Is a Humanism", "실존주의는 휴머니즘이다", ["sartre"], 1946, ["ethics"], ""),
    ("work:autobiographical-notes", "Autobiographical Notes", "자전적 노트", ["einstein"], 1949, ["physics"], ""),
    ("work:the-rebel", "The Rebel", "반항하는 인간", ["camus"], 1951, ["ethics", "political-philosophy"], ""),
    ("work:philosophical-investigations", "Philosophical Investigations", "철학적 탐구", ["wittgenstein"], 1953,
     ["philosophy-of-language"], "사후 출간"),
    ("work:two-concepts-of-liberty", "Two Concepts of Liberty", "자유의 두 개념", ["berlin"], 1958,
     ["political-philosophy"], "옥스퍼드 취임 강연"),
    ("work:constitution-of-liberty", "The Constitution of Liberty", "자유헌정론", ["hayek"], 1960,
     ["political-philosophy", "economics"], ""),
    ("work:nietzsche-lectures", "Nietzsche (lectures 1936–1946)", "니체 강의", ["heidegger"], 1961, ["metaphysics"], "1961년 출간"),
    ("work:structure-scientific-revolutions", "The Structure of Scientific Revolutions", "과학혁명의 구조", ["kuhn"], 1962,
     ["philosophy-of-science"], ""),
    ("work:conjectures-refutations", "Conjectures and Refutations", "추측과 논박", ["popper"], 1963,
     ["philosophy-of-science"], ""),
    ("work:logic-or-psychology", "Logic of Discovery or Psychology of Research?", "발견의 논리인가 탐구의 심리학인가?",
     ["kuhn"], 1970, ["philosophy-of-science"], "Lakatos & Musgrave (eds.), Criticism and the Growth of Knowledge"),
    ("work:theory-of-justice", "A Theory of Justice", "정의론", ["rawls"], 1971, ["political-philosophy"], ""),
]
