"""Phase 1 seed — 명제.

명제는 원문 인용이 아니라 해당 대목의 '요지(paraphrase)'다. locator 는 표준 인용 체계
(스테파누스·베커 쪽수, 장·절, 판본 쪽수 등)를 따른다. 원문 인용문(quotation)은 검토자가
원전을 확인해 증거에 붙이도록 비워 두었다.

(key, author, work, year, locator, statement_ko, statement_en, concepts)
"""

PROPOSITIONS = [
    # Socrates (via Plato)
    ("socrates-ignorance", "socrates", "apology", -399, "21d",
     "나는 내가 알지 못한다는 것을 안다는 점에서 남보다 조금 더 지혜롭다.",
     "Socrates is wiser only in that he does not think he knows what he does not know.", ["socratic-method"]),
    ("socrates-examined-life", "socrates", "apology", -399, "38a",
     "검토되지 않은 삶은 인간에게 살 가치가 없다.",
     "The unexamined life is not worth living for a human being.", ["socratic-method", "virtue"]),
    # Plato
    ("plato-justice-functional", "plato", "republic", -375, "IV 433a–b",
     "정의로운 국가는 각 계층이 자신의 고유한 기능을 수행하고 남의 일에 간섭하지 않을 때 성립한다.",
     "Justice in the city is each class doing its own work and not meddling with others'.",
     ["justice", "ideal-state", "division-of-labor", "virtue"]),
    ("plato-city-division-of-labor", "plato", "republic", -375, "II 369b–370c",
     "국가는 인간이 자족하지 못하기 때문에 생기며, 각자가 본성에 맞는 한 가지 일에 전념할 때 더 많은 것을 더 잘 생산한다.",
     "A city arises from need; more and better goods are produced when each does the one job suited to his nature.",
     ["division-of-labor", "ideal-state"]),
    ("plato-cave", "plato", "republic", -375, "VII 514a–517c",
     "감각적 세계는 동굴 벽의 그림자와 같고, 참된 실재는 이성으로만 파악되는 이데아의 세계다.",
     "The sensible world is like shadows on a cave wall; true reality is the intelligible world of Forms.",
     ["forms", "objective-truth", "idealism"]),
    ("plato-philosopher-kings", "plato", "republic", -375, "V 473c–d",
     "철학자가 통치하거나 통치자가 철학을 하지 않는 한 국가의 불행은 끝나지 않는다.",
     "Until philosophers rule or rulers philosophize, there will be no end to the troubles of cities.",
     ["philosopher-king", "ideal-state"]),
    ("plato-recollection", "plato", "meno", -385, "81c–86b",
     "배움이란 영혼이 이미 알고 있던 것을 상기하는 것이다.",
     "Learning is recollection of what the soul already knows.", ["anamnesis", "innate-ideas", "rationalism"]),
    # Aristotle
    ("aristotle-critique-forms", "aristotle", "metaphysics", -340, "A.9 990b–991b",
     "이데아가 사물과 분리되어 존재한다면 그것은 사물의 존재도, 운동도, 인식도 설명하지 못한다.",
     "Separately existing Forms explain neither the being, the change, nor the knowledge of things.",
     ["forms", "substance", "hylomorphism"]),
    ("aristotle-four-causes", "aristotle", "physics", -350, "II.3 194b",
     "사물을 안다는 것은 그 질료인·형상인·운동인·목적인을 아는 것이다.",
     "To know a thing is to grasp its material, formal, efficient and final causes.", ["four-causes", "teleology"]),
    ("aristotle-eudaimonia", "aristotle", "nicomachean-ethics", -340, "I.7 1098a",
     "인간의 좋음(행복)은 완전한 삶에서 덕에 따르는 영혼의 활동이다.",
     "The human good is activity of soul in accordance with virtue over a complete life.", ["eudaimonia", "virtue", "teleology"]),
    ("aristotle-money-measure", "aristotle", "nicomachean-ethics", -340, "V.5 1133a",
     "화폐는 서로 다른 재화를 공통의 척도로 잴 수 있게 하여 교환의 정의를 가능케 한다.",
     "Money makes different goods commensurable and so makes just exchange possible.", ["just-exchange", "justice"]),
    ("aristotle-private-property", "aristotle", "politics", -340, "II.5 1262b–1264b",
     "재산은 사적으로 소유하되 사용은 공동으로 하는 것이 낫다 — 플라톤식 재산 공유는 분쟁과 태만을 낳는다.",
     "Property should be private in ownership but common in use; Plato's communism of property breeds neglect and strife.",
     ["private-property", "ideal-state"]),
    ("aristotle-political-animal", "aristotle", "politics", -340, "I.2 1253a",
     "인간은 본성상 폴리스적 동물이다.", "Man is by nature a political animal.", ["teleology", "natural-law"]),
    # Hellenistic
    ("epicurus-death", "epicurus", "letter-to-menoeceus", -300, "124–127",
     "죽음은 우리에게 아무것도 아니다 — 우리가 있을 때 죽음은 없고, 죽음이 있을 때 우리는 없다.",
     "Death is nothing to us: when we are, death is not; when death is, we are not.", ["ataraxia", "materialism"]),
    ("epicurus-pleasure", "epicurus", "letter-to-menoeceus", -300, "131–132",
     "우리가 말하는 쾌락은 방탕이 아니라 몸의 고통과 마음의 동요가 없는 상태다.",
     "The pleasure we mean is absence of pain in the body and of trouble in the soul.", ["ataraxia", "eudaimonia"]),
    ("epictetus-control", "epictetus", "enchiridion", 125, "1",
     "어떤 것은 우리에게 달려 있고 어떤 것은 그렇지 않다 — 자유는 우리에게 달린 것에만 마음을 두는 데 있다.",
     "Some things are up to us and some are not; freedom lies in attending only to what is up to us.",
     ["inner-freedom", "freedom", "determinism"]),
    # Augustine
    ("augustine-free-will", "augustine", "de-libero-arbitrio", 395, "I–II",
     "악은 신이 아니라 인간 의지의 자유로운 선택에서 비롯된다.",
     "Evil originates not from God but from the free choice of the human will.", ["free-will", "freedom"]),
    ("augustine-si-fallor", "augustine", "city-of-god", 426, "XI.26",
     "내가 속는다면 나는 존재한다 — 속는 자는 존재해야 하기 때문이다.",
     "If I am deceived, I exist; for one who does not exist cannot be deceived.", ["cogito", "skepticism"]),
    ("augustine-two-cities", "augustine", "city-of-god", 426, "XIV.28",
     "두 사랑이 두 도성을 만들었다 — 신을 멸시하는 자기 사랑의 지상 도성과 자기를 멸시하는 신의 사랑의 천상 도성.",
     "Two loves built two cities: the earthly by love of self, the heavenly by love of God.", ["two-cities"]),
    # Aquinas
    ("aquinas-five-ways", "aquinas", "summa-theologiae", 1270, "I q.2 a.3",
     "신의 존재는 운동·능동인·우연성·완전성의 정도·목적 지향성으로부터 다섯 가지 길로 증명될 수 있다.",
     "God's existence can be proved in five ways: from motion, efficient causation, contingency, gradation, and governance.",
     ["god-existence", "teleology", "faith-and-reason"]),
    ("aquinas-natural-law", "aquinas", "summa-theologiae", 1270, "I-II q.94 a.2",
     "자연법의 제1원리는 '선은 행하고 추구하며 악은 피하라'이며, 인간의 자연적 경향성이 그 내용을 이룬다.",
     "The first precept of natural law is that good is to be done and pursued and evil avoided, grounded in natural inclinations.",
     ["natural-law", "teleology"]),
    ("aquinas-grace-nature", "aquinas", "summa-theologiae", 1270, "I q.1 a.8 ad 2",
     "은총은 자연을 파괴하지 않고 완성한다.", "Grace does not destroy nature but perfects it.", ["faith-and-reason"]),
    ("aquinas-just-price", "aquinas", "summa-theologiae", 1270, "II-II q.77 a.1",
     "물건을 그 가치보다 비싸게 파는 것은 교환의 정의에 어긋난다.",
     "To sell a thing for more than its worth is contrary to the justice of exchange.", ["just-price", "just-exchange"]),
    ("aquinas-property", "aquinas", "summa-theologiae", 1270, "II-II q.66 a.2",
     "사유재산은 인간 이성이 자연법에 덧붙인 것으로 정당하나, 사용에 있어서는 공동의 필요에 열려 있어야 한다.",
     "Private possession is lawful as an addition of human reason to natural law, but use should serve common need.",
     ["private-property", "natural-law"]),
    # Machiavelli
    ("machiavelli-effectual-truth", "machiavelli", "the-prince", 1513, "ch. 15",
     "상상된 국가가 아니라 사물의 실제적 진실을 따라야 한다 — 선하지 않을 줄 아는 법을 배워야 한다.",
     "Go to the effectual truth of the thing rather than imagined republics; a prince must learn to be able not to be good.",
     ["political-realism"]),
    ("machiavelli-feared", "machiavelli", "the-prince", 1513, "ch. 17",
     "둘 다 가질 수 없다면 사랑받는 것보다 두려움의 대상이 되는 편이 안전하다.",
     "It is safer to be feared than loved, if one cannot be both.", ["political-realism", "sovereignty"]),
    # Hobbes
    ("hobbes-state-of-war", "hobbes", "leviathan", 1651, "ch. 13",
     "공통의 권력이 없는 자연상태는 만인에 대한 만인의 전쟁이며, 그곳에서 인간의 삶은 고독하고 가난하고 험악하고 잔인하고 짧다.",
     "Without a common power, the state of nature is a war of all against all, and life is solitary, poor, nasty, brutish, and short.",
     ["state-of-nature", "social-contract-concept"]),
    ("hobbes-sovereign", "hobbes", "leviathan", 1651, "ch. 17",
     "평화를 위해 사람들은 신약을 맺어 자신의 권리를 하나의 주권자에게 양도한다.",
     "For peace, men covenant to confer their power on one sovereign.", ["sovereignty", "social-contract-concept"]),
    ("hobbes-liberty", "hobbes", "leviathan", 1651, "ch. 21",
     "자유란 운동에 대한 외부적 장애가 없는 것이다.",
     "Liberty signifies the absence of external impediments to motion.", ["negative-freedom", "determinism"]),
    # Descartes
    ("descartes-doubt", "descartes", "meditations", 1641, "Meditation I",
     "조금이라도 의심할 수 있는 것은 모두 거짓으로 간주하고, 확실한 토대를 찾을 때까지 판단을 유보한다.",
     "Whatever admits the slightest doubt is to be treated as false until a certain foundation is found.", ["skepticism"]),
    ("descartes-cogito", "descartes", "discourse-on-method", 1637, "Part IV",
     "나는 생각한다, 그러므로 나는 존재한다.", "I think, therefore I am.", ["cogito", "rationalism"]),
    ("descartes-dualism", "descartes", "meditations", 1641, "Meditation VI",
     "정신은 사유하는 비연장적 실체이고 물체는 연장된 비사유적 실체로서, 실재적으로 구별된다.",
     "Mind, an unextended thinking thing, is really distinct from body, an extended non-thinking thing.",
     ["mind-body-dualism", "substance", "mechanism"]),
    ("descartes-analytic-geometry", "descartes", "la-geometrie", 1637, "Book I",
     "기하학의 모든 문제는 몇몇 선분의 길이를 알면 작도할 수 있는 형태로, 즉 대수 방정식으로 환원될 수 있다.",
     "Any problem in geometry can be reduced to terms such that knowing the lengths of certain lines suffices — i.e., to algebraic equations.",
     ["analytic-geometry", "mathematization-of-nature"]),
    # Spinoza
    ("spinoza-one-substance", "spinoza", "ethics-spinoza", 1677, "I prop. 14",
     "신 외에는 어떤 실체도 존재할 수 없고 생각될 수도 없다.",
     "Except God, no substance can be or be conceived.", ["substance-monism", "substance"]),
    ("spinoza-freedom", "spinoza", "ethics-spinoza", 1677, "I def. 7",
     "자유로운 것이란 오직 자기 본성의 필연성에 의해 존재하고 스스로에 의해서만 행위하도록 결정되는 것이다.",
     "That thing is free which exists from the necessity of its own nature alone and is determined to act by itself alone.",
     ["freedom-as-necessity", "determinism"]),
    ("spinoza-no-free-will", "spinoza", "ethics-spinoza", 1677, "II prop. 48",
     "정신 안에는 절대적 또는 자유로운 의지가 없다 — 정신은 원인에 의해 이것 또는 저것을 의욕하도록 결정된다.",
     "In the mind there is no absolute or free will; it is determined to will this or that by a cause.",
     ["free-will", "determinism"]),
    ("spinoza-against-final-causes", "spinoza", "ethics-spinoza", 1677, "I appendix",
     "자연이 목적을 위해 작용한다는 생각은 인간의 편견에서 나온 것이다.",
     "The notion that nature acts for ends is a human prejudice.", ["teleology", "mechanism"]),
    ("spinoza-freedom-to-philosophize", "spinoza", "ttp", 1670, "ch. 20",
     "자유로운 국가에서는 누구나 원하는 것을 생각하고 생각하는 것을 말할 수 있어야 한다.",
     "In a free state everyone may think what he likes and say what he thinks.", ["epistemic-freedom", "political-freedom"]),
    # Locke
    ("locke-white-paper", "locke", "essay-human-understanding", 1689, "I; II.i.2",
     "정신은 처음에 아무 글자도 없는 백지와 같으며, 모든 관념은 경험에서 온다.",
     "The mind is at first like white paper, void of all characters; all ideas come from experience.",
     ["tabula-rasa", "empiricism", "innate-ideas"]),
    ("locke-law-of-nature", "locke", "two-treatises", 1689, "II §6",
     "자연상태에는 자연법이 있어, 누구도 타인의 생명·건강·자유·소유를 해쳐서는 안 된다.",
     "The state of nature has a law of nature: no one ought to harm another in his life, health, liberty, or possessions.",
     ["natural-law", "natural-rights", "state-of-nature"]),
    ("locke-property-labor", "locke", "two-treatises", 1689, "II §27",
     "자신의 노동을 섞은 것은 그의 소유가 된다.",
     "Whatever he mixes his labour with becomes his property.", ["labor-theory-of-property", "private-property"]),
    # Leibniz
    ("leibniz-veins-marble", "leibniz", "new-essays", 1704, "Preface",
     "정신은 백지가 아니라 결이 있는 대리석과 같아서, 관념과 진리는 경향성으로 본유한다.",
     "The mind is not a blank tablet but like veined marble; ideas and truths are innate as inclinations.",
     ["innate-ideas", "rationalism", "tabula-rasa"]),
    ("leibniz-reminiscence", "leibniz", "discourse-on-metaphysics", 1686, "§26",
     "플라톤의 상기설은 잘 이해하면 매우 견고하다 — 정신은 이미 모든 관념을 잠재적으로 지닌다.",
     "Plato's doctrine of reminiscence, properly understood, is sound: the mind virtually contains all its ideas.",
     ["anamnesis", "innate-ideas"]),
    ("leibniz-windowless", "leibniz", "monadology", 1714, "§7",
     "모나드에는 무엇이 드나들 수 있는 창이 없다.", "Monads have no windows through which anything could enter or leave.",
     ["monad", "substance"]),
    ("leibniz-best-world", "leibniz", "monadology", 1714, "§§53–55",
     "신은 가능한 세계들 가운데 최선의 세계를 선택했다.", "God chose the best of all possible worlds.",
     ["best-possible-world", "god-existence"]),
    ("leibniz-relational-space", "leibniz", "leibniz-clarke", 1716, "3rd letter §4",
     "공간은 절대적 실재가 아니라 공존하는 사물들의 질서에 불과하다.",
     "Space is nothing but an order of coexisting things, not an absolute reality.", ["relational-space", "absolute-space"]),
    # Newton
    ("newton-gravitation", "newton", "principia", 1687, "Book III",
     "모든 물체는 질량의 곱에 비례하고 거리의 제곱에 반비례하는 힘으로 서로를 끌어당긴다.",
     "Every body attracts every other with a force proportional to their masses and inversely to the square of distance.",
     ["universal-gravitation", "mathematization-of-nature", "calculus"]),
    ("newton-absolute-space", "newton", "principia", 1687, "Scholium to the Definitions",
     "절대공간은 그 본성상 외부의 어떤 것과도 무관하게 항상 동일하고 부동하다.",
     "Absolute space, in its own nature, without relation to anything external, remains always similar and immovable.",
     ["absolute-space"]),
    ("newton-hypotheses", "newton", "principia", 1713, "General Scholium (2nd ed.)",
     "나는 가설을 꾸며내지 않는다 — 현상에서 연역되지 않는 것은 실험철학에 자리가 없다.",
     "I frame no hypotheses; whatever is not deduced from phenomena has no place in experimental philosophy.",
     ["experimental-method"]),
    # Hume
    ("hume-induction", "hume", "enquiry-human-understanding", 1748, "§IV",
     "경험에서 얻은 모든 추론은 미래가 과거와 닮을 것이라는 가정에 기초하며, 이 가정은 이성으로 증명될 수 없다.",
     "All inferences from experience presuppose that the future will resemble the past, which reason cannot prove.",
     ["problem-of-induction", "empiricism", "skepticism"]),
    ("hume-uniformity", "hume", "enquiry-human-understanding", 1748, "§IV part ii",
     "인과 추론은 논증적(demonstrative)이지 않으며, 개연적 추론으로 정당화하려 하면 순환에 빠진다.",
     "Causal inference is not demonstrative, and justifying it by probable reasoning is circular.", ["problem-of-induction"]),
    ("hume-reason-passions", "hume", "treatise-human-nature", 1739, "2.3.3",
     "이성은 정념의 노예이며, 또 노예여야만 한다.",
     "Reason is, and ought only to be, the slave of the passions.", ["empiricism", "is-ought"]),
    ("hume-is-ought", "hume", "treatise-human-nature", 1740, "3.1.1",
     "'이다'에서 '해야 한다'로 넘어가는 추론은 설명되지 않은 비약이다.",
     "The move from 'is' to 'ought' is an unexplained leap in reasoning.", ["is-ought"]),
    # Rousseau
    ("rousseau-chains", "rousseau", "social-contract", 1762, "I.1",
     "인간은 자유롭게 태어났으나 어디서나 사슬에 묶여 있다.",
     "Man is born free, and everywhere he is in chains.", ["freedom", "political-freedom", "social-contract-concept"]),
    ("rousseau-moral-liberty", "rousseau", "social-contract", 1762, "I.8",
     "욕구의 충동에만 따르는 것은 노예 상태이고, 스스로 부과한 법에 복종하는 것이 자유다.",
     "Impulse of appetite alone is slavery; obedience to a law one prescribes to oneself is liberty.",
     ["moral-freedom", "general-will"]),
    ("rousseau-forced-free", "rousseau", "social-contract", 1762, "I.7",
     "일반의지에 복종하기를 거부하는 자는 공동체 전체에 의해 복종하도록 강제될 것이며, 이는 그가 자유롭도록 강제된다는 뜻이다.",
     "Whoever refuses to obey the general will shall be compelled to do so — he will be forced to be free.",
     ["general-will", "positive-freedom", "collectivism"]),
    ("rousseau-natural-man", "rousseau", "discourse-inequality", 1755, "Part I",
     "홉스는 사회에서 얻은 정념을 자연인에게 투사했다 — 자연상태의 인간은 호전적이지 않고 연민을 지닌다.",
     "Hobbes projected socially acquired passions onto natural man; man in the state of nature is not warlike and has pity.",
     ["state-of-nature"]),
    # Smith
    ("smith-division-of-labor", "smith", "wealth-of-nations", 1776, "I.i",
     "노동생산력의 가장 큰 향상은 분업의 결과다 — 핀 공장의 예.",
     "The greatest improvement in the productive powers of labour is the effect of the division of labour (the pin factory).",
     ["division-of-labor"]),
    ("smith-butcher", "smith", "wealth-of-nations", 1776, "I.ii",
     "우리가 저녁을 기대하는 것은 푸줏간·양조장·빵집 주인의 자비가 아니라 그들의 자기이익에 대한 관심 덕분이다.",
     "It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest.",
     ["self-interest", "division-of-labor"]),
    ("smith-invisible-hand", "smith", "wealth-of-nations", 1776, "IV.ii",
     "개인은 자신의 이익만을 의도하지만 보이지 않는 손에 이끌려 의도하지 않은 목적, 곧 사회의 이익을 증진한다.",
     "Intending only his own gain, he is led by an invisible hand to promote an end which was no part of his intention.",
     ["invisible-hand", "self-interest", "economic-freedom"]),
    # Kant
    ("kant-experience", "kant", "critique-of-pure-reason", 1787, "B1",
     "모든 인식은 경험과 함께 시작되지만, 그렇다고 모두 경험에서 생겨나는 것은 아니다.",
     "All our cognition begins with experience, but it does not all arise from experience.",
     ["synthetic-a-priori", "rationalism", "empiricism"]),
    ("kant-synthetic-apriori", "kant", "critique-of-pure-reason", 1787, "B19",
     "선험적 종합판단은 어떻게 가능한가가 순수이성의 본래 과제다.",
     "The real problem of pure reason is: how are synthetic a priori judgments possible?",
     ["synthetic-a-priori", "transcendental-idealism", "problem-of-induction"]),
    ("kant-plato-ideas", "kant", "critique-of-pure-reason", 1781, "A313/B370",
     "플라톤의 '이데아'는 경험에서 결코 빌려올 수 없는 것으로서, 그 표현이 가리키려던 바를 우리는 그 자신보다 더 잘 이해할 수 있다.",
     "Plato's 'ideas' are never borrowed from the senses; we may understand him better than he understood himself.",
     ["forms", "transcendental-idealism"]),
    ("kant-dogmatic-slumber", "kant", "prolegomena", 1783, "4:260",
     "흄의 경고가 여러 해 전 나를 독단의 잠에서 깨웠다.",
     "Hume's remark first interrupted my dogmatic slumber.", ["problem-of-induction", "skepticism"]),
    ("kant-categorical-imperative", "kant", "groundwork", 1785, "4:421",
     "네 행위의 준칙이 보편적 법칙이 되기를 네가 동시에 의욕할 수 있는 준칙에 따라서만 행위하라.",
     "Act only on that maxim through which you can at the same time will that it become a universal law.",
     ["categorical-imperative", "moral-freedom"]),
    ("kant-autonomy", "kant", "groundwork", 1785, "4:440",
     "의지의 자율은 모든 도덕 법칙과 그에 따르는 의무의 유일한 원리다.",
     "Autonomy of the will is the sole principle of all moral laws and duties.", ["moral-freedom", "categorical-imperative"]),
    ("kant-sapere-aude", "kant", "what-is-enlightenment", 1784, "8:35",
     "계몽이란 스스로 책임져야 할 미성년 상태에서 벗어나는 것이다 — 감히 알려고 하라!",
     "Enlightenment is emergence from self-incurred immaturity. Sapere aude!", ["enlightenment-concept", "moral-freedom"]),
    # Hegel
    ("hegel-true-whole", "hegel", "phenomenology-of-spirit", 1807, "Preface §20",
     "참된 것은 전체다.", "The true is the whole.", ["absolute-spirit", "dialectic"]),
    ("hegel-lordship-bondage", "hegel", "phenomenology-of-spirit", 1807, "§§178–196",
     "자기의식은 다른 자기의식의 인정을 통해서만 존재하며, 주인과 노예의 투쟁은 노동을 통해 역전된다.",
     "Self-consciousness exists only in being acknowledged; the master–slave struggle is reversed through labor.",
     ["dialectic", "freedom"]),
    ("hegel-rational-actual", "hegel", "philosophy-of-right", 1820, "Preface",
     "이성적인 것은 현실적이고, 현실적인 것은 이성적이다.", "What is rational is actual; and what is actual is rational.",
     ["absolute-spirit", "idealism"]),
    ("hegel-history-freedom", "hegel", "lectures-philosophy-of-history", 1837, "Introduction",
     "세계사는 자유의 의식의 진보다.", "World history is the progress of the consciousness of freedom.",
     ["freedom-as-necessity", "dialectic", "positive-freedom"]),
    # Schopenhauer
    ("schopenhauer-representation", "schopenhauer", "world-as-will", 1818, "§1",
     "세계는 나의 표상이다.", "The world is my representation.", ["idealism", "transcendental-idealism"]),
    ("schopenhauer-will", "schopenhauer", "world-as-will", 1818, "Book II",
     "표상의 이면, 곧 칸트의 물자체는 맹목적이고 끝없는 의지다.",
     "Behind representation, Kant's thing-in-itself, lies blind, ceaseless will.", ["will-schopenhauer"]),
    # Kierkegaard
    ("kierkegaard-subjectivity", "kierkegaard", "concluding-postscript", 1846, "Part II ch. 2",
     "진리는 주체성이다.", "Truth is subjectivity.", ["truth-as-subjectivity", "existentialism-concept"]),
    ("kierkegaard-teleological-suspension", "kierkegaard", "fear-and-trembling", 1843, "Problema I",
     "신앙은 윤리적인 것의 목적론적 정지를 요구한다 — 아브라함은 부조리에 힘입어 믿는다.",
     "Faith involves a teleological suspension of the ethical; Abraham believes by virtue of the absurd.",
     ["leap-of-faith", "absurd"]),
    # Marx / Engels
    ("marx-theses-11", "marx", "theses-on-feuerbach", 1845, "Thesis XI",
     "철학자들은 세계를 다양하게 해석해 왔을 뿐이다. 중요한 것은 세계를 변화시키는 것이다.",
     "Philosophers have only interpreted the world in various ways; the point is to change it.",
     ["historical-materialism", "materialism"]),
    ("marx-class-struggle", "marx", "communist-manifesto", 1848, "Section I",
     "지금까지 존재한 모든 사회의 역사는 계급투쟁의 역사다.",
     "The history of all hitherto existing society is the history of class struggles.",
     ["class-struggle", "historical-materialism"]),
    ("marx-abolish-property", "marx", "communist-manifesto", 1848, "Section II",
     "공산주의자의 이론은 '사적 소유의 폐지'라는 한 문장으로 요약될 수 있다.",
     "The theory of the Communists may be summed up in the single sentence: abolition of private property.",
     ["private-property", "collectivism"]),
    ("marx-alienation", "marx", "manuscripts-1844", 1844, "Estranged Labour",
     "자본주의에서 노동자는 노동의 생산물·노동 과정·유적 존재·다른 인간으로부터 소외된다.",
     "Under capitalism the worker is estranged from the product, the activity, his species-being, and other people.",
     ["alienation", "division-of-labor"]),
    ("marx-surplus-value", "marx", "capital", 1867, "chs. 6–7",
     "노동력은 자신의 가치보다 더 많은 가치를 창출하는 유일한 상품이며, 그 차이가 잉여가치다.",
     "Labour-power is the one commodity that creates more value than it has; the difference is surplus value.",
     ["surplus-value", "labor-theory-of-value"]),
    ("marx-dialectic-inverted", "marx", "capital", 1873, "Afterword to 2nd German ed.",
     "헤겔에게서 변증법은 머리로 서 있다 — 신비한 껍질 속의 합리적 핵심을 찾으려면 그것을 바로 세워야 한다.",
     "With Hegel the dialectic is standing on its head; it must be turned right side up to find the rational kernel.",
     ["dialectic", "historical-materialism", "materialism"]),
    ("marx-realm-of-freedom", "marx", "capital", 1894, "Vol. III ch. 48",
     "자유의 왕국은 필요와 외적 목적에 의해 규정되는 노동이 멈추는 곳에서 비로소 시작된다.",
     "The realm of freedom begins only where labour determined by necessity and external expediency ends.",
     ["positive-freedom", "freedom-as-necessity"]),
    ("marx-opium", "marx", "critique-hegel-right-intro", 1844, "",
     "종교는 억압받는 피조물의 한숨이며 인민의 아편이다 — 종교 비판은 모든 비판의 전제다.",
     "Religion is the sigh of the oppressed creature… the opium of the people; the criticism of religion is the premise of all criticism.",
     ["critique-of-religion", "alienation", "ideology-critique"]),
    ("marx-ruling-ideas", "marx", "german-ideology", 1846, "Part I",
     "각 시대의 지배적 사상은 지배계급의 사상이다.",
     "The ideas of the ruling class are in every epoch the ruling ideas.", ["ideology-critique", "historical-materialism"]),
    ("marx-melts-into-air", "marx", "communist-manifesto", 1848, "Section I",
     "부르주아 시대에는 굳어진 모든 것이 녹아 사라지고, 신성한 모든 것이 모독된다.",
     "All that is solid melts into air, all that is holy is profaned.", ["modernity", "class-struggle"]),
    # Nietzsche
    ("nietzsche-last-man", "nietzsche", "zarathustra", 1883, "Prologue §5",
     "'마지막 인간'은 작은 쾌락과 안락만을 원하며 '우리는 행복을 발명했다'며 눈을 깜박인다 — 근대의 평준화에 대한 경고.",
     "The 'last man' wants only small pleasures and comfort and blinks: 'We have invented happiness' — a warning against modern levelling.",
     ["modernity", "nihilism"]),
    ("nietzsche-god-dead", "nietzsche", "gay-science", 1882, "§125",
     "신은 죽었다. 그리고 우리가 그를 죽였다.", "God is dead, and we have killed him.",
     ["nihilism", "critique-of-religion", "modernity"]),
    ("nietzsche-eternal-recurrence", "nietzsche", "gay-science", 1882, "§341",
     "지금 살고 있는 이 삶을 무한히 다시 살아야 한다면 — 이 생각을 긍정할 수 있는가?",
     "Could you affirm living this very life again innumerable times?", ["eternal-recurrence"]),
    ("nietzsche-slave-revolt", "nietzsche", "genealogy-of-morals", 1887, "I §10",
     "도덕에서의 노예 반란은 원한(ressentiment)이 창조적이 되어 가치를 낳을 때 시작된다.",
     "The slave revolt in morality begins when ressentiment itself becomes creative and gives birth to values.",
     ["master-slave-morality", "ideology-critique", "critique-of-religion"]),
    ("nietzsche-will-to-power", "nietzsche", "beyond-good-and-evil", 1886, "§13, §36",
     "살아 있는 것은 무엇보다 자신의 힘을 발산하려 한다 — 생 자체가 힘에의 의지다.",
     "A living thing seeks above all to discharge its strength; life itself is will to power.", ["will-to-power"]),
    ("nietzsche-platonism-people", "nietzsche", "beyond-good-and-evil", 1886, "Preface",
     "기독교는 대중을 위한 플라톤주의다.", "Christianity is Platonism for the people.", ["forms", "nihilism"]),
    ("nietzsche-true-world-fable", "nietzsche", "twilight-of-idols", 1889, "How the 'True World' Finally Became a Fable",
     "'참된 세계'는 결국 우화가 되었다 — 참된 세계를 없애면 가상의 세계도 함께 사라진다.",
     "The 'true world' finally became a fable; with the true world we have also abolished the apparent one.",
     ["forms", "relativism", "nihilism"]),
    ("nietzsche-perspective", "nietzsche", "genealogy-of-morals", 1887, "III §12",
     "오직 관점적 봄, 관점적 인식만이 있을 뿐이다.", "There is only a perspective seeing, only a perspective knowing.",
     ["relativism", "objective-truth"]),
    ("nietzsche-causa-sui", "nietzsche", "beyond-good-and-evil", 1886, "§21",
     "자기원인(causa sui)으로서의 자유의지는 지금까지 고안된 최고의 자기모순이다.",
     "Free will as causa sui is the best self-contradiction conceived so far.", ["free-will"]),
    # Husserl
    ("husserl-things-themselves", "husserl", "logical-investigations", 1900, "Introduction §2",
     "사태 자체로 돌아가라.", "Back to the things themselves.", ["phenomenology-concept", "intentionality"]),
    ("husserl-epoche", "husserl", "ideas-i", 1913, "§32",
     "자연적 태도의 일반 정립을 괄호치고 판단을 중지함으로써 순수 의식의 장이 열린다.",
     "By bracketing the general thesis of the natural attitude, the field of pure consciousness is disclosed.",
     ["epoche", "phenomenology-concept"]),
    # Heidegger
    ("heidegger-question-of-being", "heidegger", "being-and-time", 1927, "§§1–2",
     "존재의 의미에 대한 물음은 망각되었으며 다시 제기되어야 한다.",
     "The question of the meaning of Being has been forgotten and must be raised anew.", ["being"]),
    ("heidegger-dasein-existence", "heidegger", "being-and-time", 1927, "§9",
     "현존재의 '본질'은 그의 실존에 있다.", "The 'essence' of Dasein lies in its existence.",
     ["dasein", "existentialism-concept"]),
    ("heidegger-das-man", "heidegger", "being-and-time", 1927, "§27",
     "일상적 현존재는 '세인(das Man)' 속에 빠져 비본래적으로 존재한다.",
     "Everyday Dasein is absorbed in the 'they' and exists inauthentically.", ["authenticity", "dasein"]),
    # Russell / Wittgenstein
    ("russell-descriptions", "russell", "on-denoting", 1905, "",
     "'현재 프랑스 왕은 대머리다' 같은 문장은 논리적 분석을 통해 지시어 없는 존재 주장으로 풀어야 한다.",
     "Sentences like 'the present King of France is bald' are analysed into existential claims without a denoting subject.",
     ["logical-analysis"]),
    ("russell-logicism", "russell", "principia-mathematica", 1910, "",
     "수학은 논리학의 공리와 규칙으로부터 도출될 수 있다.", "Mathematics can be derived from logical axioms and rules.",
     ["logicism", "logical-analysis"]),
    ("wittgenstein-world-facts", "wittgenstein", "tractatus", 1921, "1, 1.1",
     "세계는 일어나는 일의 총체다. 세계는 사물이 아니라 사실의 총체다.",
     "The world is everything that is the case; the totality of facts, not of things.", ["picture-theory", "logical-analysis"]),
    ("wittgenstein-picture", "wittgenstein", "tractatus", 1921, "2.1",
     "우리는 사실들의 그림을 만든다 — 명제는 실재의 그림이다.", "We picture facts to ourselves; a proposition is a picture of reality.",
     ["picture-theory"]),
    ("wittgenstein-silence", "wittgenstein", "tractatus", 1921, "7",
     "말할 수 없는 것에 대해서는 침묵해야 한다.", "Whereof one cannot speak, thereof one must be silent.", ["picture-theory"]),
    ("wittgenstein-meaning-use", "wittgenstein", "philosophical-investigations", 1953, "§43",
     "많은 경우 낱말의 의미는 언어 안에서의 그 쓰임이다.", "For a large class of cases, the meaning of a word is its use in the language.",
     ["language-game"]),
    ("wittgenstein-family-resemblance", "wittgenstein", "philosophical-investigations", 1953, "§§66–67",
     "'놀이'들에 공통된 본질은 없고, 서로 겹치고 교차하는 유사성의 그물 — 가족유사성 — 이 있을 뿐이다.",
     "There is no common essence to 'games', only a network of overlapping similarities — family resemblances.",
     ["language-game"]),
    # Einstein
    ("einstein-no-ether", "einstein", "special-relativity", 1905, "Introduction",
     "빛의 속도 불변과 상대성 원리로부터, 절대 정지 공간과 발광 에테르는 불필요하다.",
     "Given the relativity principle and the constancy of light speed, an absolutely stationary space and a luminiferous ether are superfluous.",
     ["relativity", "absolute-space"]),
    # Keynes / Hayek / Ricardo
    ("ricardo-comparative-advantage", "ricardo", "principles-political-economy", 1817, "ch. 7",
     "영국과 포르투갈의 예에서 보듯, 두 나라 모두 상대적으로 유리한 재화에 특화하면 무역으로 이익을 얻는다.",
     "As in the England–Portugal example, both countries gain from trade by specializing where their comparative advantage lies.",
     ["comparative-advantage", "division-of-labor"]),
    ("ricardo-labor-value", "ricardo", "principles-political-economy", 1817, "ch. 1",
     "상품의 가치는 그 생산에 필요한 상대적 노동량에 달려 있다.",
     "The value of a commodity depends on the relative quantity of labour necessary for its production.",
     ["labor-theory-of-value"]),
    ("keynes-effective-demand", "keynes", "general-theory", 1936, "ch. 3",
     "고용 수준은 유효수요에 의해 결정되며, 시장이 스스로 완전고용을 보장하지 않는다.",
     "The level of employment is determined by effective demand; markets do not automatically secure full employment.",
     ["effective-demand"]),
    ("keynes-classical-special-case", "keynes", "general-theory", 1936, "ch. 1",
     "고전파 이론의 공준은 일반적 경우가 아니라 특수한 경우에만 적용된다.",
     "The postulates of the classical theory apply only to a special case, not the general case.",
     ["effective-demand", "invisible-hand"]),
    ("hayek-knowledge", "hayek", "use-of-knowledge", 1945, "",
     "경제 문제는 누구에게도 전체로 주어지지 않은 분산된 지식의 활용 문제이며, 가격 체계가 그 정보를 전달한다.",
     "The economic problem is using knowledge not given to anyone in its totality; the price system communicates it.",
     ["dispersed-knowledge", "spontaneous-order", "central-planning"]),
    ("hayek-serfdom", "hayek", "road-to-serfdom", 1944, "",
     "중앙계획은 필연적으로 개인의 자유를 침해하며 전체주의로 이어진다.",
     "Central planning necessarily encroaches on individual freedom and leads toward totalitarianism.",
     ["central-planning", "individualism", "economic-freedom", "negative-freedom"]),
    ("hayek-spontaneous-order", "hayek", "constitution-of-liberty", 1960, "ch. 4",
     "많은 사회 제도는 인간 행위의 결과이지만 인간 설계의 결과는 아니다 — 스미스·퍼거슨의 전통.",
     "Many institutions are the result of human action but not of human design — the tradition of Smith and Ferguson.",
     ["spontaneous-order", "invisible-hand"]),
    # Popper / Kuhn
    ("popper-falsifiability", "popper", "logic-scientific-discovery", 1934, "§6",
     "경험과학의 체계는 경험에 의해 반증될 수 있어야 한다 — 이것이 구획 기준이다.",
     "It must be possible for an empirical scientific system to be refuted by experience; this is the criterion of demarcation.",
     ["falsifiability", "problem-of-induction"]),
    ("popper-solution-induction", "popper", "conjectures-refutations", 1963, "ch. 1",
     "흄이 옳았다 — 귀납은 정당화될 수 없다. 과학은 귀납이 아니라 추측과 논박으로 진보한다.",
     "Hume was right that induction cannot be justified; science proceeds by conjectures and refutations, not induction.",
     ["problem-of-induction", "falsifiability"]),
    ("popper-open-society", "popper", "open-society", 1945, "Vol. I–II",
     "플라톤·헤겔·마르크스의 역사주의와 전체론은 열린사회의 적이다.",
     "The historicism and holism of Plato, Hegel and Marx are enemies of the open society.",
     ["open-society", "ideal-state", "historical-materialism"]),
    ("kuhn-paradigm", "kuhn", "structure-scientific-revolutions", 1962, "chs. II–V",
     "정상과학은 패러다임 안에서의 퍼즐 풀이이며, 패러다임 자체는 반증되어 폐기되기보다 과학혁명을 통해 교체된다.",
     "Normal science is puzzle-solving within a paradigm; paradigms are replaced through revolutions rather than simply falsified.",
     ["paradigm", "falsifiability"]),
    ("kuhn-incommensurability", "kuhn", "structure-scientific-revolutions", 1962, "ch. X",
     "패러다임 전환 이후 과학자들은 다른 세계에서 일하며, 경쟁하는 패러다임은 공통 척도로 비교되기 어렵다.",
     "After a paradigm shift scientists work in a different world; rival paradigms are incommensurable.",
     ["paradigm", "relativism"]),
    # Existentialists
    ("sartre-existence-essence", "sartre", "existentialism-humanism", 1946, "",
     "실존은 본질에 앞선다 — 인간은 먼저 존재하고, 그 후에 스스로를 규정한다.",
     "Existence precedes essence: man first exists, and then defines himself.",
     ["existentialism-concept", "existential-freedom"]),
    ("sartre-condemned-free", "sartre", "existentialism-humanism", 1946, "",
     "인간은 자유롭도록 선고받았다.", "Man is condemned to be free.", ["existential-freedom", "freedom"]),
    ("sartre-bad-faith", "sartre", "being-and-nothingness", 1943, "Part I ch. 2",
     "자기기만은 자신의 자유를 부정하고 스스로를 사물처럼 여기는 태도다.",
     "Bad faith is denying one's own freedom by treating oneself as a thing.", ["bad-faith", "existential-freedom"]),
    ("camus-sisyphus", "camus", "myth-of-sisyphus", 1942, "final chapter",
     "우리는 행복한 시지프를 상상해야 한다.", "One must imagine Sisyphus happy.", ["absurd"]),
    ("camus-philosophical-suicide", "camus", "myth-of-sisyphus", 1942, "Philosophical Suicide",
     "키르케고르의 신앙의 도약은 부조리를 없애 버리는 철학적 자살이다.",
     "Kierkegaard's leap of faith is a philosophical suicide that suppresses the absurd.", ["absurd", "leap-of-faith"]),
    ("camus-rebel", "camus", "the-rebel", 1951, "Introduction",
     "나는 반항한다, 그러므로 우리는 존재한다.", "I rebel — therefore we exist.", ["absurd", "freedom"]),
    # Mill / Berlin / Rawls / Jefferson
    ("mill-harm-principle", "mill", "on-liberty", 1859, "ch. 1",
     "문명사회의 구성원에게 그의 의사에 반해 권력을 행사할 수 있는 유일한 정당한 목적은 타인에 대한 해악을 막는 것이다.",
     "The only purpose for which power can be rightfully exercised over any member of a civilised community, against his will, is to prevent harm to others.",
     ["harm-principle", "negative-freedom", "individualism"]),
    ("mill-freedom-of-thought", "mill", "on-liberty", 1859, "ch. 2",
     "한 사람을 제외한 전 인류가 같은 의견이라도, 그 한 사람의 입을 막는 것은 정당화될 수 없다.",
     "If all mankind minus one were of one opinion, mankind would be no more justified in silencing that one.",
     ["epistemic-freedom"]),
    ("mill-greatest-happiness", "mill", "utilitarianism", 1863, "ch. 2",
     "행위는 행복을 증진하는 정도에 비례해 옳고, 불행을 낳는 정도에 비례해 그르다.",
     "Actions are right in proportion as they tend to promote happiness, wrong as they produce the reverse.",
     ["utilitarianism"]),
    ("berlin-two-concepts", "berlin", "two-concepts-of-liberty", 1958, "I–II",
     "자유에는 간섭의 부재라는 소극적 개념과 자기 지배라는 적극적 개념이 있으며, 후자는 '진정한 자아'의 이름으로 강제를 정당화하는 데 오용될 수 있다.",
     "Liberty has a negative sense (non-interference) and a positive sense (self-mastery); the latter can be abused to justify coercion in the name of a 'true self'.",
     ["negative-freedom", "positive-freedom", "freedom"]),
    ("rawls-veil", "rawls", "theory-of-justice", 1971, "§§3, 24",
     "정의의 원칙은 자신의 사회적 지위와 재능을 모르는 무지의 베일 뒤 원초적 입장에서 선택된 것이다.",
     "The principles of justice are those chosen in an original position behind a veil of ignorance.",
     ["veil-of-ignorance", "justice-as-fairness", "social-contract-concept"]),
    ("rawls-two-principles", "rawls", "theory-of-justice", 1971, "§11",
     "각 개인은 기본적 자유에 대해 평등한 권리를 가지며, 사회경제적 불평등은 최소수혜자에게 이익이 되도록 편성되어야 한다.",
     "Each person has an equal right to basic liberties; social and economic inequalities must benefit the least advantaged.",
     ["justice-as-fairness", "political-freedom", "justice"]),
    ("rawls-against-utilitarianism", "rawls", "theory-of-justice", 1971, "§5",
     "공리주의는 개인들 사이의 차이를 진지하게 고려하지 않는다.",
     "Utilitarianism does not take seriously the distinction between persons.", ["utilitarianism", "justice-as-fairness"]),
    ("jefferson-unalienable-rights", "jefferson", "declaration-of-independence", 1776, "Preamble",
     "모든 사람은 평등하게 창조되었고, 생명·자유·행복 추구를 포함한 양도할 수 없는 권리를 부여받았다.",
     "All men are created equal, endowed with unalienable rights, among them life, liberty and the pursuit of happiness.",
     ["natural-rights", "political-freedom"]),
]

# 논증 구조: (arg key, label_ko, premises, conclusion, form)
ARGUMENTS = [
    ("cogito-argument", "코기토 논증", ["descartes-doubt"], "descartes-cogito", "방법적 회의 → 의심하는 나의 존재는 의심 불가"),
    ("hume-induction-argument", "흄의 귀납 논증", ["hume-uniformity"], "hume-induction",
     "귀납은 논증적 추론도 아니고, 개연적 추론으로 정당화하면 순환이다"),
    ("popper-deductivism", "포퍼의 연역주의", ["hume-induction", "popper-falsifiability"], "popper-solution-induction",
     "귀납은 정당화 불가 + 반증은 연역적으로 타당 → 과학은 추측과 논박"),
]
